name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=sha,format=long
          latest

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy-to-unraid:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Unraid
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UNRAID_HOST }}
        username: ${{ secrets.UNRAID_USERNAME }}
        password: ${{ secrets.UNRAID_PASSWORD }}
        port: ${{ secrets.UNRAID_SSH_PORT }}
        script: |
          # Pull the latest image
          docker pull ghcr.io/${{ github.repository }}:latest
          
          # Stop and remove the existing container if it exists
          docker stop music-sharing-app || true
          docker rm music-sharing-app || true
          
          # Run the new container
          docker run -d \
            --name music-sharing-app \
            -p 8080:80 \
            -e API_URL=${{ secrets.API_URL }} \
            --restart unless-stopped \
            ghcr.io/${{ github.repository }}:latest